version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  build_deploy:
    jobs:

      - build

jobs:
  build:
    docker:

      - image: circleci/node

    working_directory: ~/repo
    steps:

      - checkout
      - run: yarn install